# Generated by Django 3.2.5 on 2022-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220819_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(default='Hey there!', max_length=500),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.CharField(choices=[('1', 'BSC PM'), ('2', 'BSC CSM'), ('3', 'BCOM'), ('4', 'BBA'), ('5', 'BCA'), ('6', 'BA JPE'), ('7', 'BSC PSY CS'), ('8', ' BSC CM')], default=1, max_length=32),
        ),
    ]
